# Tugas_Sesi1.Js
// Identitas
const nama = "Endin Sya'dudin";
const nim = "20220040255";

console.log("Identitas : ");
console.log("Nama : " + nama);
console.log("Nim : " + nim);

// Operasi Aritmatika Sederhana
const angka1 = 20;
const angka2 = 4;

const tambah = angka1 + angka2;
const kurang = angka1 - angka2;
const kali = angka1 * angka2;
const bagi = angka1 / angka2;

console.log("Operasi Aritmatika : ");
console.log(`${angka1} + ${angka2} = ${tambah}`);
console.log(`${angka1} - ${angka2} = ${kurang}`);
console.log(`${angka1} * ${angka2} = ${kali}`);
console.log(`${angka1} / ${angka2} = ${bagi}`);
